// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts", true);
user_pref("app.normandy.user_id", "eb13769e-c975-4d55-8372-6f850b96d3a7");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1552601066);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1552601186);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1552604186);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1552600826);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1552600706);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1552600946);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1552351006);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1552601306);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 870400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1552348610);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"28130\":1552605977606,\"35338\":1552605977606,\"35342\":1552605977606}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.spoc.impressions", "{\"788\":[1552348617411,1552350624708,1552606169869]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{58f433f4-63c6-4581-9151-1ddea85fa406}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google,amazon");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1552539600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true},{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1552605955447");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1552607766447");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1552604173540");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1552607773540");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1552600564");
user_pref("browser.slowStartup.averageTime", 6309);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20190215001155");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1552348620872");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "713211f6a26f46299a4502ae78292df8");
user_pref("extensions.blocklist.lastModified", "Thu, 14 Mar 2019 12:52:21 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1552601066);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190128144255");
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{85cb5383-6791-4d13-a1f3-0516cfe19771}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"},\"webcompat@mozilla.org\":{\"version\":\"3.0.1\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"f72b9c82-5073-4493-94f3-6911aa1ef90b\",\"screenshots@mozilla.org\":\"6838a6a9-9c59-4e56-98b7-18e94a67512d\",\"webcompat-reporter@mozilla.org\":\"05f9ce7a-b3cf-4b97-a4b6-791e3aa293ba\",\"webcompat@mozilla.org\":\"8b7aece9-d484-4dbc-abe8-f9ca7debb39a\",\"fxmonitor@mozilla.org\":\"e5057cb5-010f-4a7b-b60f-857ceefdc818\"}");
user_pref("idle.lastDailyNotification", 1552600805);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1552349113);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190215001155");
user_pref("media.gmp-manager.lastCheck", 1552600664);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1552352134);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "4a46f744-4ce6-4391-a8e4-9d046e242846");
user_pref("security.sandbox.plugin.tempDirSuffix", "2c763002-61c6-43fd-a797-7dd9b8913122");
user_pref("services.blocklist.addons.checked", 1552600800);
user_pref("services.blocklist.gfx.checked", 1552600800);
user_pref("services.blocklist.onecrl.checked", 1552600800);
user_pref("services.blocklist.pinning.checked", 1552600800);
user_pref("services.blocklist.plugins.checked", 1552600800);
user_pref("services.settings.clock_skew_seconds", -165);
user_pref("services.settings.last_etag", "\"1552589019976\"");
user_pref("services.settings.last_update_seconds", 1552601111);
user_pref("services.settings.main.language-dictionaries.last_check", 1552600800);
user_pref("services.settings.main.onboarding.last_check", 1552600800);
user_pref("services.settings.main.sites-classification.last_check", 1552600800);
user_pref("services.settings.main.tippytop.last_check", 1552600800);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1552352134);
user_pref("toolkit.startup.last_success", 1552600550);
user_pref("toolkit.telemetry.cachedClientID", "b02dde07-dfee-4f65-90bb-7428460a1d83");
user_pref("toolkit.telemetry.previousBuildID", "20190215001155");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
